import type { Holding } from "@/lib/types";

const t0 = Date.parse("2026-04-18T09:30:00+05:30");

export const SAMPLE_HOLDINGS: Holding[] = [
  {
    id: "hld_rel",
    name: "Reliance Industries",
    type: "indian_stock",
    ticker: "RELIANCE",
    exchange: "NSE",
    quantity: 12,
    avgPrice: 1284,
    currency: "INR",
    costBasisInr: 15408,
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "hld_infy",
    name: "Infosys",
    type: "indian_stock",
    ticker: "INFY",
    exchange: "NSE",
    quantity: 20,
    avgPrice: 1472,
    currency: "INR",
    costBasisInr: 29440,
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "hld_aapl",
    name: "Apple",
    type: "us_stock",
    ticker: "AAPL",
    exchange: "US",
    quantity: 8,
    avgPrice: 192.4,
    currency: "USD",
    costBasisInr: 131_520,
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "hld_ppfas",
    name: "Parag Parikh Flexi Cap Direct Growth",
    type: "indian_mf",
    ticker: "122639",
    quantity: 185.52,
    avgPrice: 72.4,
    currency: "INR",
    costBasisInr: 13432,
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "hld_bees",
    name: "Nippon India Nifty 50 BeES",
    type: "etf",
    ticker: "NIFTYBEES",
    exchange: "NSE",
    quantity: 150,
    avgPrice: 245,
    currency: "INR",
    costBasisInr: 36750,
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "hld_gold",
    name: "Family jewellery",
    type: "physical_gold",
    quantity: 48,
    avgPrice: 6250,
    currency: "INR",
    costBasisInr: 300000,
    purity: 22,
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "hld_aia",
    name: "Tata AIA Individual Life - Equity",
    type: "ulip",
    ticker: "ITA065",
    quantity: 4200,
    avgPrice: 72,
    currency: "INR",
    costBasisInr: 302400,
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "hld_usd",
    name: "USD savings",
    type: "usd_cash",
    quantity: 3200,
    avgPrice: 83.1,
    currency: "USD",
    costBasisInr: 265920,
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "hld_hdfc",
    name: "HDFC Bank savings",
    type: "bank",
    quantity: 285000,
    avgPrice: 1,
    currency: "INR",
    costBasisInr: 285000,
    manualValueInr: 285000,
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "hld_rd",
    name: "SBI recurring deposit",
    type: "rd",
    quantity: 1,
    avgPrice: 90000,
    currency: "INR",
    costBasisInr: 90000,
    manualValueInr: 96480,
    notes: "₹5,000 / month, 18 months elapsed",
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "hld_fd",
    name: "ICICI tax-saver FD",
    type: "fd",
    quantity: 1,
    avgPrice: 500000,
    currency: "INR",
    costBasisInr: 500000,
    manualValueInr: 538200,
    createdAt: t0,
    updatedAt: t0,
  },
  {
    id: "hld_ppf",
    name: "Public Provident Fund",
    type: "other",
    quantity: 1,
    avgPrice: 310000,
    currency: "INR",
    costBasisInr: 310000,
    manualValueInr: 348600,
    notes: "PPF, SBI",
    createdAt: t0,
    updatedAt: t0,
  },
];
