/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HoldingsHoldingIdRouteImport } from './routes/holdings_.$holdingId'
import { Route as HoldingsNewRouteImport } from './routes/holdings_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsHoldingIdRoute = HoldingsHoldingIdRouteImport.update({
  id: '/holdings_/$holdingId',
  path: '/holdings/$holdingId',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsNewRoute = HoldingsNewRouteImport.update({
  id: '/holdings_/new',
  path: '/holdings/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/holdings': typeof HoldingsRoute
  '/settings': typeof SettingsRoute
  '/holdings/$holdingId': typeof HoldingsHoldingIdRoute
  '/holdings/new': typeof HoldingsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/holdings': typeof HoldingsRoute
  '/settings': typeof SettingsRoute
  '/holdings/$holdingId': typeof HoldingsHoldingIdRoute
  '/holdings/new': typeof HoldingsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/holdings': typeof HoldingsRoute
  '/settings': typeof SettingsRoute
  '/holdings_/$holdingId': typeof HoldingsHoldingIdRoute
  '/holdings_/new': typeof HoldingsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/holdings' | '/settings' | '/holdings/$holdingId' | '/holdings/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/holdings' | '/settings' | '/holdings/$holdingId' | '/holdings/new'
  id:
    | '__root__'
    | '/'
    | '/holdings'
    | '/settings'
    | '/holdings_/$holdingId'
    | '/holdings_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HoldingsRoute: typeof HoldingsRoute
  SettingsRoute: typeof SettingsRoute
  HoldingsHoldingIdRoute: typeof HoldingsHoldingIdRoute
  HoldingsNewRoute: typeof HoldingsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings_/$holdingId': {
      id: '/holdings_/$holdingId'
      path: '/holdings/$holdingId'
      fullPath: '/holdings/$holdingId'
      preLoaderRoute: typeof HoldingsHoldingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings_/new': {
      id: '/holdings_/new'
      path: '/holdings/new'
      fullPath: '/holdings/new'
      preLoaderRoute: typeof HoldingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HoldingsRoute: HoldingsRoute,
  SettingsRoute: SettingsRoute,
  HoldingsHoldingIdRoute: HoldingsHoldingIdRoute,
  HoldingsNewRoute: HoldingsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
